### ISSUE TITLE
Decide on basic tech-stack

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/swiss-sculptures#2]
Decide on the techstack:
- what JS framework do you want to use?
- what Mapping-component do you want to use?

And then make sure it runs on the hardware.

**Comment by ZEDz318** [comment]
The tech stack I'll use for now : 

- Svelte
- Tailwind
- Maplibre

**Comment by flicksolutions** [comment]
Sounds good!
What are you going to use for the image-gallery?
