### ISSUE TITLE
create basic structure of the app

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/swiss-sculptures#4]
Create a basic structure of the app. this includes:
- what components does the app consist of
- what is the dataflow
- what are possible interactions and actions

**Comment by ZEDz318** [comment]
For now i am thinking of two svelte components, a Map component and a Popup component. 

- The map is straight forward with points and lines, and the Popup component is shown when a point is clicked on the map.

- The Popup component is just a slideshow (for the images) and text fields

- When a point is clicked, two popup components will show (for and and new), with different styling (position) depending on the type of data (old to the left and new to the right).

**Comment by flicksolutions** [comment]
Sounds good!
How is the flow of data? Is your input a .xslx that you will convert to CSV or JSON?

Then where is the data read and interpreted? On the page that holds the two components? Is the popup getting information via props, or is it reading out of a [store](https://learn.svelte.dev/tutorial/writable-stores)?
