### ISSUE TITLE
get rid of API key in sourcecode

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/swiss-sculptures#7]
You have your maptiler API key in your source code here:

https://github.com/DHBern/swiss-sculptures/blob/3a47de55c4fd382f9571402eea0fb4a174eae670/swiss-sculptures-map/src/routes/Map.svelte#L51C71-L51C91

Please create a new API Key (invalidate the old one) and use it with an env-variable.

**Comment by ZEDz318** [comment]
Done 👍

**Comment by flicksolutions** [comment]
thanks! Next time, please mention the commit (8cd38b4c8ba8e17a3072e8203481d6b93e25df1f) here in the comment, or the issue in the commit message so that the two are linked
