### ISSUE TITLE
get build to run

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/swiss-sculptures#8]
In order to finish #3 you first need to be able to build the app an run it.

For this your app needs some changes:
- [x] use [adapter-node](https://kit.svelte.dev/docs/adapter-node) instead of adapter-auto
- [x] https://github.com/DHBern/swiss-sculptures/blob/8cd38b4c8ba8e17a3072e8203481d6b93e25df1f/swiss-sculptures-map/src/app.html#L7 is left over from tailwind. you can delete the line and the file. (it won't find the file in the build app and create an error if not)

**Comment by ZEDz318** [comment]
I will commit this in a few, but it is solved.
