### ISSUE TITLE
Software solutions to lock down a computer to a single browser

### ISSUE THREAD

**Issue by ZEDz318** [DHBern/swiss-sculptures#9]
We still need to secure the browser. Which software should we use?

**Comment by flicksolutions** [comment]
What we are looking for is Kiosk mode. Two years ago when I had the challenge to do this, I used this guide: https://itnext.io/raspberry-pi-read-only-kiosk-mode-2022-complete-tutorial-df7fc051fdaf
But of course by now there are other tutorials like [this one](https://www.raspberrypi.com/tutorials/how-to-use-a-raspberry-pi-in-kiosk-mode/).

In the end this startup sequence should be configured:
 - boot up
 - log in to wifi
 - pull changes from github repository
 - build app
 - run node app
 - start chromium browser

If done like this, the pi can also be unplugged during the nights and startup correctly again without the staff knowing anything about the system.

**Comment by ZEDz318** [comment]
I used kiosk and cron to do this.
Now on boot-up, all the points above are executed
